/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jusenr_chat_jninative_NativeContent */

#ifndef _Included_com_jusenr_chat_jninative_NativeContent
#define _Included_com_jusenr_chat_jninative_NativeContent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jusenr_chat_jninative_NativeContent
 * Method:    decode
 * Signature: ([BIIZIIII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_jusenr_chat_jninative_NativeContent_decode
        (JNIEnv *,
         jobject,
         jbyteArray,
         jint,
         jint,
         jboolean,
         jint,
         jint,
         jint,
         jint);


JNIEXPORT jstring JNICALL
Java_com_jusenr_chat_jninative_NativeContent_stringFromJNI(
        JNIEnv *,
        jobject);

#ifdef __cplusplus
}
#endif
#endif
